apiVersion: v1
kind: Pod
metadata:
  name: dev-pod-merve
  labels:
    app: dev
spec:
  containers:
  - name: dev-container-merve
    image: mervezeybel/devpod # Build and push the image with this tag
    ports:
    - containerPort: 22
    volumeMounts:
    - mountPath: /workspace
      name: workspace-volume
  volumes:
  - name: workspace-volume
    emptyDir: {}
  restartPolicy: Always